In [3]:
from google.colab import drive
drive.mount('/content/drive')

path = '/content/drive/My Drive/ciencias de dados/adult.zip'

Mounted at /content/drive

In [4]:
import zipfile
import pandas as pd

# Caminho do arquivo ZIP
path = '/content/drive/My Drive/ciencias de dados/adult.zip'

# Extrair o conteúdo
with zipfile.ZipFile(path, 'r') as zip_ref:
    zip_ref.extractall('/content/adult_dataset')

# Conferir os arquivos extraídos
import os
print(os.listdir('/content/adult_dataset'))

['adult.names', 'adult.test', 'adult.data', 'old.adult.names', 'Index']

In [5]:
colunas = [
    'age',
    'workclass',
    'fnlwgt',
    'education',
    'education-num',
    'marital-status',
    'occupation',
    'relationship',
    'race',
    'sex',
    'capital-gain',
    'capital-loss',
    'hours-per-week',
    'native-country',
    'income'
]

df = pd.read_csv(
    '/content/adult_dataset/adult.data',
    header=None,
    names=colunas,
    skipinitialspace=True
)

df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [6]:
# IMPORTAÇÕES
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler

# GOOGLE DRIVE
from google.colab import drive
drive.mount('/content/drive')

# CAMINHO DO ARQUIVO
path = '/content/drive/My Drive/ciencias de dados/adult.zip'

# EXTRAÇÃO
import zipfile

with zipfile.ZipFile(path, 'r') as zip_ref:
    zip_ref.extractall('/content/adult_dataset')

# NOMES DAS COLUNAS
colunas = [
    'age',
    'workclass',
    'fnlwgt',
    'education',
    'education-num',
    'marital-status',
    'occupation',
    'relationship',
    'race',
    'sex',
    'capital-gain',
    'capital-loss',
    'hours-per-week',
    'native-country',
    'income'
]

# CARREGAMENTO
df = pd.read_csv(
    '/content/adult_dataset/adult.data',
    header=None,
    names=colunas,
    skipinitialspace=True
)

df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K